POSTS_PATH = 'C:\\here_your\\absolute_path\\to\\data\\posts.json'
COMMENTS_PATH = 'C:\\here_your\\absolute_path\\to\\data\\comments.json'
BOOKMARKS_PATH = 'C:\\here_your\\absolute_path\\to\\data\\bookmarks.json'
GET_POSTS_DATA = 'C:\\here_your\\absolute_path\\to\\data\\get_posts_data.json'
GET_POSTS_DATA_SINGLE = 'C:\\here_your\\absolute_path\\to\\data\\get_posts_data_single.json'
